IMAGE_NAME_TIME_FORMAT = "%M%S"
TIME_FORMAT_EYETRACKING = "%H:%M:%S.%f"
TIME_FORMAT_HR = "%H:%M:%S"
TIME_FORMAT = "%H:%M:%S"
DATA_COLUMN_COUNT = 4
DELIMITER = ','
FILE_EXTENSION = ".jpeg"
LAST_DIR_FILE = 'path_info.json'

WINDOW_HEIGHT = 600
